djangoProject5/My_Blog/urls.py
from django.urls import path
from . import views,models
from My_Blog.feeds import AllPostsRssFeed
app_name = 'My_Blog'

urlpatterns = [
    path('', views.IndexView.as_view(),name='index'),#使用.as_view函数来引用类函数IndexView
    #根据views中post加文章id来添加urls
    path('post/<int:pk>/',views.PostDetailView.as_view(),name='detail'),
    #为view中根据文章时间:created_time来filter过滤，添加urls
    path('archives/<int:year>/<int:month>/', views.ArchiveView.as_view(), name='archive'),
    #为views中category的过滤信息来添加
    path('categories/<int:pk>/', views.CategoryView.as_view(), name='category'),
    #为views中Tag的过滤信息来添加
    path('tags/<int:pk>/',views.TagView.as_view(),name='tag'),
    #为全文搜索添加url
    path('search/', views.search, name='search'),


    ##以下方式存疑，不推荐，硬编码
    path('index.html',views.IndexView.as_view(),name='index'),
    # path('full-width.html',views.index,name='index'),
    # path('about.html',views.index,name='index'),
    # path('contact.html',views.index,name='index'),
]

djangoProject5/djangoProject5/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path,include
from My_Blog.feeds import AllPostsRssFeed
urlpatterns = [
    path('admin/', admin.site.urls),
    path('My_Blog/',include('My_Blog.urls')),
    path('',include('My_Blog.urls')),
    path('', include('comments.urls')),
    # 添加rss订阅url
    path('all/rss/', AllPostsRssFeed(), name='rss'),

]

djangoProject5/My_Blog/models.py
import re 
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.urls import reverse
import markdown
from django.utils.functional import cached_property
from django.utils.html import strip_tags
from markdown.extensions.toc import TocExtension, slugify


class Category(models.Model):
    name = models.CharField(max_length=50)
    class Meta:
        verbose_name = '文章分类'
        verbose_name_plural = verbose_name
    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=50)
    class Meta:
        verbose_name = '文章标签'
        verbose_name_plural = verbose_name
    def __str__(self):
        return self.name


def generate_rich_content(value):
    md = markdown.Markdown(
        extensions=[
            "markdown.extensions.extra",
            "markdown.extensions.codehilite",
            # 记得在顶部引入 TocExtension 和 slugify
            TocExtension(slugify=slugify),
        ]
    )
    content = md.convert(value)
    m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>', md.toc, re.S)
    toc = m.group(1) if m is not None else ""
    return {"content": content, "toc": toc}


class Post(models.Model):
    title = models.CharField(max_length=200,verbose_name='标题')
    body = models.TextField(verbose_name='正文')
    # 一对多
    category = models.ForeignKey(Category, on_delete=models.CASCADE,verbose_name='分类')
    #多对多
    tag = models.ManyToManyField(Tag,blank=True,verbose_name='标签')
    # 一篇文章只能有一个作者，而一个作者可以有多篇文章，所以为一对多
    author = models.ForeignKey(User, on_delete=models.CASCADE,verbose_name='作者')
    created_time = models.DateTimeField(verbose_name='创作时间',default=timezone.now)#自动保存首次创建模型的时间
    modified_time = models.DateTimeField(verbose_name='修改时间')
    excerpt = models.CharField(max_length=50,blank=True)
    #记录浏览量
    views = models.PositiveIntegerField(default=0, editable=False)

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-created_time']

    def save(self, *args, **kwargs):
        self.modified_time = timezone.now()

        # 首先实例化一个 Markdown 类，用于渲染 body 的文本。
        # 由于摘要并不需要生成文章目录，所以去掉了目录拓展。
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
        ])

        # 先将 Markdown 文本渲染成 HTML 文本
        # strip_tags 去掉 HTML 文本的全部 HTML 标签
        # 从文本摘取前 54 个字符赋给 excerpt
        self.excerpt = strip_tags(md.convert(self.body))[:54]

        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('My_Blog:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

    # 写一个方法记录浏览量
    def increase_views(self):
        self.views +=1
        self.save(update_fields=['views'])

    @property
    def toc(self):
        return self.rich_content.get("toc", "")

    @property
    def body_html(self):
        return self.rich_content.get("content", "")

    @cached_property
    def rich_content(self):
        return generate_rich_content(self.body)


djangoProject5/comments/models.py
from django.db import models
from django.utils import timezone
# Create your models here.
##创建评论类，以及属性
class Comments(models.Model):
    name = models.CharField('名字',max_length=25)
    email = models.CharField('邮箱地址',max_length=50)
    url = models.URLField('网址',blank=True)#可以为空
    text = models.TextField('评论内容')
    created_time = models.DateTimeField('创建时间',default=timezone.now)
    post = models.ForeignKey('My_Blog.Post',verbose_name='文章',on_delete=models.CASCADE)#实现一对一外键，链接到Post类的post文章

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name #当为复数的时候，同verbose_name（单复数一致）

    def __str__(self):
        return '{}: {}'.format(self.name, self.text[:20])

djangoProject5/My_Blog/views.py
from django.db.models import Q
from django.shortcuts import render,get_object_or_404,redirect
from pure_pagination.mixins import PaginationMixin

from My_Blog.models import Post,Category,Tag
from django.views.generic import  ListView,DetailView
from django.contrib import messages

# def index(request):
#     post_list = Post.objects.all().order_by('-created_time')
#     return render(request, template_name='My_Blog/index.html', context={'post_list':post_list})
#将上述视图函数改为类视图
class IndexView(ListView,PaginationMixin):
    model = Post
    template_name = 'My_Blog/index.html'
    context_object_name = 'post_list'
    paginate_by = 10

# def detail(request, pk):
#     post = get_object_or_404(Post, pk=pk)
#     #阅读量增加1
#     post.increase_views()
#
#     md = markdown.Markdown(extensions=[
#         'markdown.extensions.extra',
#         'markdown.extensions.codehilite',
#         'markdown.extensions.toc',
#         TocExtension(slugify=slugify),
#     ])
#     post.body = md.convert(post.body)
#     m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>', md.toc, re.S)
#     post.toc = m.group(1) if m is not None else ''
#     return render(request, 'My_Blog/detail.html', context={'post': post})
#将上述视图函数改为类视图
class PostDetailView(DetailView):
    model = Post
    template_name = 'My_Blog/detail.html'
    context_object_name = 'post'
    def get(self, request, *args, **kwargs):
        # 覆写 get 方法的目的是因为每当文章被访问一次，就得将文章阅读量 +1
        # get 方法返回的是一个 HttpResponse 实例
        # 之所以需要先调用父类的 get 方法，是因为只有当 get 方法被调用后，
        # 才有 self.object 属性，其值为 Post 模型实例，即被访问的文章 post
        response = super(PostDetailView, self).get(request, *args, **kwargs)
        # 将文章阅读量 +1
        # 注意 self.object 的值就是被访问的文章 post
        self.object.increase_views()
        # 视图必须返回一个 HttpResponse 对象
        return response
    # def get_object(self, queryset=None):
    #     # 覆写 get_object 方法的目的是因为需要对 post 的 body 值进行渲染
    #     post = super().get_object(queryset=None)
    #     md = markdown.Markdown(extensions=[
    #         'markdown.extensions.extra',
    #         'markdown.extensions.codehilite',
    #         # 记得在顶部引入 TocExtension 和 slugify
    #         TocExtension(slugify=slugify),
    #     ])
    #     post.body = md.convert(post.body)
    #     m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>', md.toc, re.S)
    #     post.toc = m.group(1) if m is not None else ''
    #     return post

#使用时间归档filter来过滤文章
# def archive(request, year, month):
#     post_list = Post.objects.filter(created_time__year=year,
#                                     created_time__month=month
#                                     ).order_by('-created_time')
#     return render(request, 'My_Blog/index.html', context={'post_list': post_list})
##使用类函数来改写上述视图函数
class ArchiveView(IndexView):
    def get_queryset(self):
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        return super().get_queryset().filter(created_time__year=year, created_time__month=month)


# #使用分类归档filter来过滤文章
# def category(request,pk):
#     cate = get_object_or_404(Category,pk=pk)
#     post_list = Post.objects.filter(category=cate).order_by('-created_time')
#     return render(request,'My_Blog/index.html',context={'post_list':post_list})
#使用类函数来改写上述视图函数
class CategoryView(ListView):
    model = Post
    template_name = 'My_Blog/index.html'
    context_object_name = 'post_list'
    def get_queryset(self):
        cate = get_object_or_404(Category,pk=self.kwargs.get('pk'))
        return super(CategoryView,self).get_queryset().filter(category=cate)


#使用标签归档filter来过滤文章
# def tag(request,pk):
#     t = get_object_or_404(Tag,pk=pk)
#     post_list = Post.objects.filter(tag=t).order_by('-created_time')
#     return render(request,'My_Blog/index.html',context={'post_list':post_list})
#使用类函数来改写上述视图函数
class TagView(ListView):
    model = Post
    template_name = 'My_Blog/index.html'
    context_object_name = 'post_list'
    def get_queryset(self):
        t = get_object_or_404(Tag,pk=self.kwargs.get('pk'))
        return super(TagView,self).get_queryset().filter(tag=t)

##创建一个视图函数，实现全文搜索
def search(request):
    q = request.GET.get('q')
    if not q:
        error_msg = '请输入关键词'
        messages.add_message(request,messages.ErrOR,error_msg,extra_tags='danger')
        return redirect('My_Blog:index')

    post_list = Post.objects.filter(Q(title__icontains=q) | Q(body__icontains=q))
    return render(request, 'My_Blog/index.html', {'post_list': post_list})


djangoProject5/templates/My_Blog/detail.html
{% extends 'base.html' %}
{% load comments_extras %}
{% block main %}
    <article class="post post-{{ post.pk }}">
        <header class="entry-header">
            <h1 class="entry-title">{{ post.title }}</h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                <span class="post-author"><a href="#">{{ post.author }}</a></span>
                <span class="comments-link"><a href="#comment-area">{{ post.comments_set.count }} 评论</a></span>
                <span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.views }} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{ post.body|safe }}
        </div>
    </article>
    <section class="comment-area" id="comment-area">
        <hr>
    </section>
    <h3>发表评论</h3>
    {% show_comment_form post %}
    <div class="comment-list-panel">
        {% show_comments post %}
    </div>
    <div class="entry-content clearfix">
        {{ post.body_html|safe }}
    </div>
{% endblock main %}
{% block toc %}
  {% if post.toc %}
    <div class="widget widget-content">
      <h3 class="widget-title">文章目录</h3>
      <div class="toc">
        <ul>
          {{ post.toc|safe }}
        </ul>
      </div>
    </div>
  {% endif %}
{% endblock toc %}

djangoProject5/templates/My_Blog/index.html
{% extends 'base.html' %}
{% block main %}
    {% for post in post_list %}
        <article class=" post post-{{ post.pk }}">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{{ post.get_absolute_url }}">{{ post.title}}</a>
                </h1>
                <div class="entry-meta">
                    <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                    <span class="post-date"><a href="#"><time class="entry-date"
                                                              datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                    <span class="post-author"><a href="#">{{ post.author }}</a></span>
                    <span class="comments-link"><a href="{{ post.get_absolute_url }}#comment-area">{{ post.comments_set.count }} 评论</a></span>
                    <span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.views }} 阅读</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>{{ post.excerpt }}</p>
                <div class="read-more cl-effect-14">
                    <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
    {% empty %}
        <div class="no-post">暂时还没有发布文章!</div>
    {% endfor %}
{% if is_paginated %}
<div class="pagination-simple">
  <!-- 如果当前页还有上一页，显示一个上一页的按钮 -->
  {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
  {% endif %}
  <!-- 显示当前页面信息 -->
  <span class="current">第 {{ page_obj.number }} 页 / 共 {{ paginator.num_pages }} 页</span>
  <!-- 如果当前页还有下一页，显示一个下一页的按钮 -->
  {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">下一页</a>
  {% endif %}
</div>
{% endif %}
    {% if is_paginated %}
    {{ page_obj.render }}
{% endif %}
    <!-- 简单分页效果
    <div class="pagination-simple">
        <a href="#">上一页</a>
        <span class="current">第 6 页 / 共 11 页</span>
        <a href="#">下一页</a>
    </div>
    -->
{% endblock main %}