djangoProject5/My_Blog/urls.py
from django.urls import path
from . import views,models
from My_Blog.feeds import AllPostsRssFeed
app_name = 'My_Blog'

urlpatterns = [
    path('', views.IndexView.as_view(),name='index'),#使用.as_view函数来引用类函数IndexView
    #根据views中post加文章id来添加urls
    path('post/<int:pk>/',views.PostDetailView.as_view(),name='detail'),
    #为view中根据文章时间:created_time来filter过滤，添加urls
    path('archives/<int:year>/<int:month>/', views.ArchiveView.as_view(), name='archive'),
    #为views中category的过滤信息来添加
    path('categories/<int:pk>/', views.CategoryView.as_view(), name='category'),
    #为views中Tag的过滤信息来添加
    path('tags/<int:pk>/',views.TagView.as_view(),name='tag'),
    #为全文搜索添加url
    path('search/', views.search, name='search'),


    ##以下方式存疑，不推荐，硬编码
    path('index.html',views.IndexView.as_view(),name='index'),
    # path('full-width.html',views.index,name='index'),
    # path('about.html',views.index,name='index'),
    # path('contact.html',views.index,name='index'),
]

djangoProject5/djangoProject5/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path,include
from My_Blog.feeds import AllPostsRssFeed
urlpatterns = [
    path('admin/', admin.site.urls),
    path('My_Blog/',include('My_Blog.urls')),
    path('',include('My_Blog.urls')),
    path('', include('comments.urls')),
    # 添加rss订阅url
    path('all/rss/', AllPostsRssFeed(), name='rss'),

]

djangoProject5/templates/base.html
{%load static%}
{%load My_Blog_extras%}
<!DOCTYPE html>
<html>
<head>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <title>邹佳伶的博客</title>
    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <!-- js -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/pace.min.js' %}"></script>
    <script src="{% static 'js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'js/modernizr.custom.js' %}"></script>

    <link href="https://cdn.bootcss.com/highlight.js/9.15.8/styles/github.min.css" rel="stylesheet">

    <style>
        .codehilite {
            padding: 0;
        }

        /* for block of numbers */
        .hljs-ln-numbers {
            -webkit-touch-callout: none;
            -webkit-user-select: none;
            -khtml-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;

            text-align: center;
            color: #ccc;
            border-right: 1px solid #CCC;
            vertical-align: top;
            padding-right: 5px;
        }

        .hljs-ln-n {
            width: 30px;
        }

        /* for block of code */
        .hljs-ln .hljs-ln-code {
            padding-left: 10px;
            white-space: pre;
        }
    </style>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'My_Blog:index' %}"><b>Black</b> &amp; White</a></h1>
                </div>
                <div class="rss">
                    <a href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'My_Blog:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="{% url 'My_Blog:index' %}" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="{% url 'My_Blog:index' %}" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="{% url 'My_Blog:index' %}" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'My_Blog:search' %}">
                            <input type="search" name="q" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>

            </div><!-- col-md-8 -->

        </div>
    </header>
</div>
<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}
            </main>
            <aside class="col-md-4">
                {% block toc %}
                {% endblock toc %}
                {% show_recent_posts %}
                {% show_archives %}
                {% show_categories %}
                {% show_tags %}
            </aside>
        </div>
    </div>

</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">
                    欢迎访问<a href="http://web.pkusz.edu.cn/wu/" target="_blank">深圳市计算化学与药物设计重点实验室</a>
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="{% url 'My_Blog:index' %}">首页</a></li>
            <li><a href="{% url 'My_Blog:index' %}">博客</a></li>
            <li><a href="{% url 'My_Blog:index' %}">关于</a></li>
            <li><a href="{% url 'My_Blog:index' %}">联系</a></li>
        </ul>
    </nav>
</div>
<script src="{% static 'js/script.js' %}"></script>
<script src="https://cdn.bootcss.com/highlight.js/9.15.8/highlight.min.js"></script>
<script src="https://cdn.bootcss.com/highlightjs-line-numbers.js/2.7.0/highlightjs-line-numbers.min.js"></script>
<script>
    hljs.initHighlightingOnLoad();
    hljs.initLineNumbersOnLoad();
</script>
</body>
</html>